
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/kderbyma/Library/Application Support/Herd/bin/"
      - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin/"
      - "/Users/kderbyma/.config/herd-lite/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/kderbyma/.cargo/bin/"
      - "/Users/kderbyma/.orbstack/bin/"
      - "/Users/kderbyma/Library/Python/3.9/bin/"
      - "/Users/kderbyma/.vscode/extensions/ms-python.debugpy-2025.10.0-darwin-arm64/bundled/scripts/noConfigScripts/"
      - "/Users/kderbyma/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "/Users/kderbyma/Library/Application Support/Herd/bin/uname"
      - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin/uname"
      - "/Users/kderbyma/.config/herd-lite/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/kderbyma/Library/Application Support/Herd/bin/"
        - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin"
        - "/Users/kderbyma/.config/herd-lite/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/opt/homebrew/bin"
        - "/Users/kderbyma/Library/Application Support/Herd/bin/"
        - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin"
        - "/Users/kderbyma/.config/herd-lite/bin"
        - "/Users/kderbyma/.cargo/bin"
        - "/Users/kderbyma/.orbstack/bin"
        - "/Users/kderbyma/Library/Python/3.9/bin"
        - "/Users/kderbyma/.vscode/extensions/ms-python.debugpy-2025.10.0-darwin-arm64/bundled/scripts/noConfigScripts"
        - "/Users/kderbyma/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/kderbyma/.orbstack/bin"
        - "/Users/kderbyma/Library/Python/3.9/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.4.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/kderbyma/Library/Application Support/Herd/bin/"
      - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin/"
      - "/Users/kderbyma/.config/herd-lite/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/kderbyma/.cargo/bin/"
      - "/Users/kderbyma/.orbstack/bin/"
      - "/Users/kderbyma/Library/Python/3.9/bin/"
      - "/Users/kderbyma/.vscode/extensions/ms-python.debugpy-2025.10.0-darwin-arm64/bundled/scripts/noConfigScripts/"
      - "/Users/kderbyma/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "/Users/kderbyma/Library/Application Support/Herd/bin/install_name_tool"
      - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin/install_name_tool"
      - "/Users/kderbyma/.config/herd-lite/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/kderbyma/Library/Application Support/Herd/bin/"
        - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin"
        - "/Users/kderbyma/.config/herd-lite/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/opt/homebrew/bin"
        - "/Users/kderbyma/Library/Application Support/Herd/bin/"
        - "/Users/kderbyma/Library/Application Support/Herd/config/nvm/versions/node/v22.19.0/bin"
        - "/Users/kderbyma/.config/herd-lite/bin"
        - "/Users/kderbyma/.cargo/bin"
        - "/Users/kderbyma/.orbstack/bin"
        - "/Users/kderbyma/Library/Python/3.9/bin"
        - "/Users/kderbyma/.vscode/extensions/ms-python.debugpy-2025.10.0-darwin-arm64/bundled/scripts/noConfigScripts"
        - "/Users/kderbyma/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/kderbyma/.orbstack/bin"
        - "/Users/kderbyma/Library/Python/3.9/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
