import js from '@eslint/js';
import react from 'eslint-plugin-react';

export default [
  {
    ignores: [
      'node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/.next/**',
      '**/vite-env.d.ts',
      '**/*.config.js',
      'html/**',
      'output/**',
      '**/*.min.js',
      '**/*.min.css',
      '**/*.json',
      '**/*.md',
      'packages/specs/**',
      '**/*.ts',
      '**/*.tsx',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        // Node
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        // Browser APIs
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        AbortController: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        URLSearchParams: 'readonly',
        URL: 'readonly',
        customElements: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        Intl: 'readonly',
        alert: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        location: 'readonly',
        history: 'readonly',
        Event: 'readonly',
        SVGElement: 'readonly',
        Element: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        module: 'readonly',
        // Browser APIs
        PointerEvent: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        AudioContext: 'readonly',
        getComputedStyle: 'readonly',
        performance: 'readonly',
        CustomEvent: 'readonly',
        FontFace: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        WebSocket: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        TransformStream: 'readonly',
        HTMLImageElement: 'readonly',
        self: 'readonly',
        MediaStream: 'readonly',
        MediaRecorder: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        MouseEvent: 'readonly',
        FileReader: 'readonly',
        ImageData: 'readonly',
        WebAssembly: 'readonly',
      },
    },
    rules: {
      // Errors - actual logical issues
      'no-undef': 'error',
      'no-const-assign': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-setter-return': 'error',
      'no-this-before-super': 'error',
      'no-unreachable': 'error',
      'no-unsafe-negation': 'error',
      'valid-typeof': 'error',
      'constructor-super': 'error',
      'for-direction': 'error',

      // Warnings - code quality, not blockers
      'no-var': 'warn',
      'no-unused-vars': [
        'warn',
        {
          args: 'none',
          argsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      'no-debugger': 'warn',
      'no-empty': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-fallthrough': 'warn',
      'no-irregular-whitespace': 'warn',
      'no-loss-of-precision': 'warn',
      'no-octal': 'warn',
      'no-redeclare': 'warn',
      'no-sparse-arrays': 'warn',
      'no-case-declarations': 'warn',
      'no-async-promise-executor': 'warn',
      'no-useless-escape': 'warn',
      'no-prototype-builtins': 'warn',
      'no-constant-binary-expression': 'warn',
      'no-dupe-class-members': 'warn',
      'constructor-super': 'warn',
      'no-this-before-super': 'warn',
      'no-unreachable': 'warn',
      'no-func-assign': 'warn',
      'use-isnan': 'warn',

      // Style - disabled, let prettier handle it
      indent: 'off',
      'no-tabs': 'off',
      'no-mixed-spaces-and-tabs': 'off',
      semi: 'off',
      quotes: 'off',
      'comma-dangle': 'off',
      'no-trailing-spaces': 'off',
      'eol-last': 'off',
      'keyword-spacing': 'off',
      'space-before-blocks': 'off',
      'object-curly-spacing': 'off',
      'array-bracket-spacing': 'off',
      'computed-property-spacing': 'off',
      'key-spacing': 'off',
      'no-multi-spaces': 'off',

      // Best practices - warnings only
      eqeqeq: ['warn', 'smart'],
      'no-eval': 'warn',
      'no-implied-eval': 'warn',
      'no-extend-native': 'warn',
      'no-multi-assign': 'warn',
      'no-with': 'warn',
    },
  },
  {
    files: ['**/*.jsx'],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      react,
    },
    rules: {
      'react/jsx-uses-react': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'warn',
      'react/display-name': 'warn',
    },
  },
  {
    files: ['**/__tests__/**', '**/*.test.*', '**/*.spec.*', '**/vitest.setup.js'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        jest: 'readonly',
        it: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
      },
    },
    rules: {
      'no-undef': 'warn',
    },
  },
];
