/*                                                 *\
** ----------------------------------------------- **
**             Calliope - Site Generator   	       **
** ----------------------------------------------- **
**  Copyright (c) 2020-2021 - Kyle Derby MacInnis  **
**                                                 **
**    Any unauthorized distribution or transfer    **
**       of this work is strictly prohibited.      **
**                                                 **
**               All Rights Reserved.              **
** ----------------------------------------------- **
\*                                                 */

// Tet
import T from "../tilesets/sewer/tiles.jsx";
import { Vector } from "../../engine/utils/math/vector.jsx";
import { Direction } from "../../engine/utils/enums.jsx";
// Map
export default {
  bounds: [0, 10, 17, 19],
  tileset: "sewer",
  audioSrc: "/pixos/audio/blue-fields.mp3",
  // (0,10) -> (17,19) (X, Y) (9 Rows x 17 Column)
  cells: [
    ...[
      T.SLW_CORNER,
      T.SLW_COLUMN,
      T.FLOOR,
      T.FLOOR,
      T.LW_LPIT,
      T.WATER,
      T.WATER,
      T.WATER,
      T.V_WALKWAY,
      T.WATER,
      T.WATER,
      T.WATER,
      T.RW_RPIT,
      T.FLOOR,
      T.FLOOR,
      T.SRW_COLUMN,
      T.SRW_CORNER,
    ],
    ...[
      T.EMPTY,
      T.SLW_CORNER,
      T.S_WALL,
      T.S_WALL,
      T.S_WALL,
      T.SLW_WATER_COLUMN,
      T.WATER,
      T.WATER,
      T.S_STAIR,
      T.WATER,
      T.WATER,
      T.SRW_WATER_COLUMN,
      T.S_WALL,
      T.S_WALL,
      T.S_WALL,
      T.SRW_CORNER,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.L_WALL,
      T.SW_SPIT,
      T.SW_SPIT,
      T.S_STAIRWALL,
      T.SW_SPIT,
      T.SW_SPIT,
      T.R_WALL,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.L_WALL,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.R_WALL,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.L_WALL,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.R_WALL,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.SLW_CORNER,
      T.SLW_COLUMN,
      T.FLOOR,
      T.FLOOR,
      T.FLOOR,
      T.SRW_COLUMN,
      T.SRW_CORNER,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.SLW_CORNER,
      T.S_WALL,
      T.S_WALL,
      T.S_WALL,
      T.SRW_CORNER,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
    ...[
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
      T.EMPTY,
    ],
  ],
  // Sprites and Objects to be Loaded in the Scene & their Starting Points
  sprites: [
    { id: "water", type: "npc/water-knight", pos: new Vector(...[8, 13, 0]), facing: Direction.Up },
    { id: "spurt7", type: "effects/waterspurt", pos: new Vector(...[7, 10, -1.5]), facing: Direction.Up },
    { id: "spurt9", type: "effects/waterspurt", pos: new Vector(...[10, 10, -1.5]), facing: Direction.Up },
  ],
  // Scripts / Triggers
  scripts: [
    {
      id: "load-scene",
      trigger: () => {
        console.log("Triggered");
      },
    },
  ],
  // TODO - Add in Scenes / Dialogue
  //
  scenes: [],
};
