/*                                                 *\
** ----------------------------------------------- **
**          Calliope - Pixos Game Engine           **
** ----------------------------------------------- **
**  Copyright (c) 2020-2025 - Kyle Derby MacInnis  **
**                                                 **
**    Any unauthorized distribution or transfer    **
**       of this work is strictly prohibited.      **
**                                                 **
**               All Rights Reserved.              **
** ----------------------------------------------- **
\*                                                 */

#ifndef SHADERS_H
#define SHADERS_H

// Main vertex shader for 3D rendering with texturing and lighting
static const char* MAIN_VERTEX_SHADER = 
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 aVertexPosition;\n"
"layout (location = 1) in vec3 aVertexNormal;\n"
"layout (location = 2) in vec2 aTextureCoord;\n"
"\n"
"uniform mat4 uModelMatrix;\n"
"uniform mat4 uViewMatrix;\n"
"uniform mat4 uProjectionMatrix;\n"
"uniform mat3 uNormalMatrix;\n"
"uniform vec3 uCameraPosition;\n"
"uniform vec3 uScale;\n"
"\n"
"out vec3 vFragPos;\n"
"out vec3 vWorldNormal;\n"
"out vec3 vTransformedNormal;\n"
"out vec2 vTextureCoord;\n"
"out vec3 vViewDir;\n"
"\n"
"void main() {\n"
"    vec3 scaledPosition = aVertexPosition * uScale;\n"
"    \n"
"    vec4 worldPos = uModelMatrix * vec4(scaledPosition, 1.0);\n"
"    vFragPos = vec3(worldPos);\n"
"    vTextureCoord = aTextureCoord;\n"
"    vTransformedNormal = uNormalMatrix * aVertexNormal;\n"
"    vWorldNormal = normalize(mat3(uModelMatrix) * aVertexNormal);\n"
"    vViewDir = normalize(uCameraPosition - vFragPos);\n"
"    \n"
"    gl_Position = uProjectionMatrix * uViewMatrix * worldPos;\n"
"}\n";

// Main fragment shader with lighting and texturing
static const char* MAIN_FRAGMENT_SHADER = 
"#version 330 core\n"
"\n"
"const int MAX_LIGHTS = 32;\n"
"const float NEAR = 0.1;\n"
"const float FAR = 50.0;\n"
"\n"
"struct PointLight {\n"
"    bool enabled;\n"
"    vec3 color;\n"
"    vec3 position;\n"
"    vec3 attenuation;\n"
"    float density;\n"
"};\n"
"\n"
"in vec3 vFragPos;\n"
"in vec3 vWorldNormal;\n"
"in vec3 vTransformedNormal;\n"
"in vec2 vTextureCoord;\n"
"in vec3 vViewDir;\n"
"\n"
"uniform PointLight uLights[MAX_LIGHTS];\n"
"uniform sampler2D uSampler;\n"
"uniform bool uUseSampler;\n"
"uniform vec3 uDiffuseColor;\n"
"uniform vec4 uColorMultiplier;\n"
"uniform bool uIsSelected;\n"
"uniform float uAmbientStrength;\n"
"\n"
"out vec4 FragColor;\n"
"\n"
"float getAttenuation(PointLight light) {\n"
"    vec3 toLight = light.position - vFragPos;\n"
"    float distance = length(toLight);\n"
"    float attenuation = 1.0 / (\n"
"        1.0 + light.attenuation.x +\n"
"        light.attenuation.y * distance +\n"
"        light.attenuation.z * distance * distance\n"
"    );\n"
"    return attenuation;\n"
"}\n"
"\n"
"vec3 calculateLighting(vec3 baseColor) {\n"
"    vec3 ambient = uAmbientStrength * baseColor;\n"
"    vec3 result = ambient;\n"
"    vec3 normal = normalize(vWorldNormal);\n"
"    \n"
"    for (int i = 0; i < MAX_LIGHTS; i++) {\n"
"        if (!uLights[i].enabled) continue;\n"
"        \n"
"        vec3 lightDir = normalize(uLights[i].position - vFragPos);\n"
"        float diff = max(dot(normal, lightDir), 0.0);\n"
"        vec3 diffuse = diff * uLights[i].color;\n"
"        \n"
"        // Specular\n"
"        vec3 reflectDir = reflect(-lightDir, normal);\n"
"        float spec = pow(max(dot(vViewDir, reflectDir), 0.0), 32.0);\n"
"        vec3 specular = 0.5 * spec * uLights[i].color;\n"
"        \n"
"        float attenuation = getAttenuation(uLights[i]);\n"
"        result += attenuation * (diffuse + specular) * baseColor;\n"
"    }\n"
"    \n"
"    return clamp(result, 0.0, 1.0);\n"
"}\n"
"\n"
"float linearizeDepth(float depth) {\n"
"    float z = depth * 2.0 - 1.0;\n"
"    return (2.0 * NEAR * FAR) / (FAR + NEAR - z * (FAR - NEAR));\n"
"}\n"
"\n"
"void main() {\n"
"    vec4 baseColor;\n"
"    \n"
"    if (uUseSampler) {\n"
"        baseColor = texture(uSampler, vTextureCoord);\n"
"        if (baseColor.a < 0.1) discard;\n"
"    } else {\n"
"        baseColor = vec4(uDiffuseColor, 1.0);\n"
"    }\n"
"    \n"
"    vec3 litColor = calculateLighting(baseColor.rgb);\n"
"    \n"
"    // Apply color multiplier\n"
"    litColor *= uColorMultiplier.rgb;\n"
"    \n"
"    // Selection highlight\n"
"    if (uIsSelected) {\n"
"        litColor = mix(litColor, vec3(1.0, 1.0, 0.0), 0.3);\n"
"    }\n"
"    \n"
"    // Simple fog based on depth\n"
"    float depth = linearizeDepth(gl_FragCoord.z) / FAR;\n"
"    vec3 fogColor = vec3(0.5, 0.6, 0.7);\n"
"    litColor = mix(litColor, fogColor, clamp(depth * 0.5, 0.0, 0.8));\n"
"    \n"
"    FragColor = vec4(litColor, baseColor.a * uColorMultiplier.a);\n"
"}\n";

// Simple sprite vertex shader (billboarding)
static const char* SPRITE_VERTEX_SHADER =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 aVertexPosition;\n"
"layout (location = 1) in vec2 aTextureCoord;\n"
"\n"
"uniform mat4 uModelMatrix;\n"
"uniform mat4 uViewMatrix;\n"
"uniform mat4 uProjectionMatrix;\n"
"uniform vec3 uScale;\n"
"\n"
"out vec2 vTextureCoord;\n"
"out vec3 vFragPos;\n"
"\n"
"void main() {\n"
"    vec3 scaledPosition = aVertexPosition * uScale;\n"
"    vec4 worldPos = uModelMatrix * vec4(scaledPosition, 1.0);\n"
"    vFragPos = vec3(worldPos);\n"
"    vTextureCoord = aTextureCoord;\n"
"    gl_Position = uProjectionMatrix * uViewMatrix * worldPos;\n"
"}\n";

// Simple sprite fragment shader
static const char* SPRITE_FRAGMENT_SHADER =
"#version 330 core\n"
"\n"
"in vec2 vTextureCoord;\n"
"in vec3 vFragPos;\n"
"\n"
"uniform sampler2D uSampler;\n"
"uniform vec4 uColorMultiplier;\n"
"uniform bool uIsSelected;\n"
"\n"
"out vec4 FragColor;\n"
"\n"
"void main() {\n"
"    vec4 texColor = texture(uSampler, vTextureCoord);\n"
"    if (texColor.a < 0.1) discard;\n"
"    \n"
"    vec3 color = texColor.rgb * uColorMultiplier.rgb;\n"
"    \n"
"    if (uIsSelected) {\n"
"        color = mix(color, vec3(1.0, 1.0, 0.0), 0.3);\n"
"    }\n"
"    \n"
"    FragColor = vec4(color, texColor.a * uColorMultiplier.a);\n"
"}\n";

// Picker vertex shader (for object selection)
static const char* PICKER_VERTEX_SHADER =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 aVertexPosition;\n"
"\n"
"uniform mat4 uModelMatrix;\n"
"uniform mat4 uViewMatrix;\n"
"uniform mat4 uProjectionMatrix;\n"
"uniform vec3 uScale;\n"
"\n"
"void main() {\n"
"    vec3 scaledPosition = aVertexPosition * uScale;\n"
"    gl_Position = uProjectionMatrix * uViewMatrix * uModelMatrix * vec4(scaledPosition, 1.0);\n"
"}\n";

// Picker fragment shader (outputs unique color ID)
static const char* PICKER_FRAGMENT_SHADER =
"#version 330 core\n"
"\n"
"uniform vec4 uObjectId;\n"
"\n"
"out vec4 FragColor;\n"
"\n"
"void main() {\n"
"    FragColor = uObjectId;\n"
"}\n";

// Tile vertex shader
static const char* TILE_VERTEX_SHADER =
"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 aVertexPosition;\n"
"layout (location = 1) in vec3 aVertexNormal;\n"
"layout (location = 2) in vec2 aTextureCoord;\n"
"\n"
"uniform mat4 uModelMatrix;\n"
"uniform mat4 uViewMatrix;\n"
"uniform mat4 uProjectionMatrix;\n"
"uniform mat3 uNormalMatrix;\n"
"\n"
"out vec3 vFragPos;\n"
"out vec3 vWorldNormal;\n"
"out vec2 vTextureCoord;\n"
"\n"
"void main() {\n"
"    vec4 worldPos = uModelMatrix * vec4(aVertexPosition, 1.0);\n"
"    vFragPos = vec3(worldPos);\n"
"    vTextureCoord = aTextureCoord;\n"
"    vWorldNormal = normalize(mat3(uModelMatrix) * aVertexNormal);\n"
"    gl_Position = uProjectionMatrix * uViewMatrix * worldPos;\n"
"}\n";

// Tile fragment shader
static const char* TILE_FRAGMENT_SHADER =
"#version 330 core\n"
"\n"
"in vec3 vFragPos;\n"
"in vec3 vWorldNormal;\n"
"in vec2 vTextureCoord;\n"
"\n"
"uniform sampler2D uSampler;\n"
"uniform float uAmbientStrength;\n"
"\n"
"out vec4 FragColor;\n"
"\n"
"void main() {\n"
"    vec4 texColor = texture(uSampler, vTextureCoord);\n"
"    if (texColor.a < 0.1) discard;\n"
"    \n"
"    // Simple ambient lighting for tiles\n"
"    vec3 ambient = uAmbientStrength * texColor.rgb;\n"
"    \n"
"    FragColor = vec4(ambient, texColor.a);\n"
"}\n";

#endif // SHADERS_H
